apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-api
  labels:
    app: golang-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang-api
  template:
    metadata:
      labels:
        app: golang-api
    spec:
      containers:
        - name: golang-api
          image: elsrpie/golang-api:latest
          ports:
            - containerPort: 8080